version: '3.8'

services:
  # FastAPI Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: valuation-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=${DATABASE_URL}
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - CORS_ORIGINS=http://localhost,http://localhost:80,http://localhost:4200
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - backend_logs:/app/logs
    networks:
      - valuation-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - mongodb

  # Angular Frontend Service
  frontend:
    build:
      context: ./valuation-frontend
      dockerfile: Dockerfile
    container_name: valuation-frontend
    ports:
      - "80:80"
    environment:
      - API_URL=http://backend:8000
    volumes:
      - frontend_logs:/var/log/nginx
    networks:
      - valuation-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - backend

  # MongoDB Service (optional - if not using Atlas)
  mongodb:
    image: mongo:7.0
    container_name: valuation-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-password}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME:-valuation_app}
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
      - ./scripts/mongo-init:/docker-entrypoint-initdb.d
    networks:
      - valuation-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis Service (for caching and background jobs)
  redis:
    image: redis:7-alpine
    container_name: valuation-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - valuation-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

# Volumes for persistent data
volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  redis_data:
    driver: local
  backend_logs:
    driver: local
  frontend_logs:
    driver: local

# Network for service communication
networks:
  valuation-network:
    driver: bridge