version: '3.8'

services:
  # FastAPI Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: valuation-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=${DATABASE_URL}
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - CORS_ORIGINS=http://localhost,http://localhost:80
    env_file:
      - .env
    volumes:
      - ./backend:/app:Z
      - backend_logs:/app/logs:Z
    networks:
      - valuation-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
# Volumes for persistent data
volumes:
  backend_logs:
    driver: local

# Network for service communication
networks:
  valuation-network:
    driver: bridge