#!/usr/bin/env python3
"""
Simple PDF Generation Service for Valuation Reports
Basic text-based PDF without external dependencies (development fallback)
"""

from fastapi import APIRouter, HTTPException, Response
from fastapi.responses import StreamingResponse
import json
from datetime import datetime
from typing import Dict, Any, Optional
import io

router = APIRouter()

class PDFGenerator:
    def __init__(self):
        self.templates = {
            'SBI': {
                'LAND_PROPERTY': 'sbi_land_template'
            }
        }

    def generate_pdf(self, report_data: Dict[str, Any]) -> bytes:
        """
        Generate a simple text-based PDF representation
        This is a development fallback until proper PDF libraries are configured
        """
        # Create a simple text representation that could be converted to PDF later
        text_content = self._generate_text_report(report_data)
        
        # For now, return as plain text (browser will handle as download)
        return text_content.encode('utf-8')

    def _generate_text_report(self, report_data: Dict[str, Any]) -> str:
        """
        Generate a text representation of the report
        """
        lines = []
        
        # Header
        bank_code = report_data.get('bankCode', 'Unknown Bank')
        property_type = report_data.get('propertyType', 'Property')
        report_ref = report_data.get('reportReferenceNumber', 'N/A')
        org_name = report_data.get('organizationShortName', 'Valuation Organization')
        
        lines.append("=" * 80)
        lines.append(f"{bank_code.upper()} - {property_type.upper()} PROPERTY VALUATION REPORT")
        lines.append("=" * 80)
        lines.append("")
        lines.append(f"Report Reference: {report_ref}")
        lines.append(f"Bank: {bank_code}")
        lines.append(f"Property Type: {property_type.title()}")
        lines.append(f"Organization: {org_name}")
        lines.append(f"Generated Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        lines.append("")
        lines.append("-" * 80)
        
        # Process template data
        template_data = report_data.get('templateData', {})
        form_values = report_data.get('formValues', {})
        
        if template_data and 'documents' in template_data:
            for document in template_data.get('documents', []):
                for section in document.get('sections', []):
                    section_title = section.get('title', 'Section')
                    lines.append("")
                    lines.append(f"{section_title.upper()}")
                    lines.append("-" * len(section_title))
                    
                    for field in section.get('fields', []):
                        field_id = field.get('fieldId', '')
                        field_label = field.get('label', field_id)
                        
                        # Get value from form data or field default
                        field_value = (
                            form_values.get(field_id, '') or 
                            field.get('value', '') or 
                            field.get('defaultValue', 'N/A')
                        )
                        
                        lines.append(f"{field_label}: {field_value}")
        
        # Add any additional form values not in template
        template_field_ids = set()
        if template_data and 'documents' in template_data:
            for document in template_data.get('documents', []):
                for section in document.get('sections', []):
                    for field in section.get('fields', []):
                        template_field_ids.add(field.get('fieldId', ''))
        
        other_fields = []
        for field_id, value in form_values.items():
            if field_id not in template_field_ids and value:
                other_fields.append((field_id.replace('_', ' ').title(), str(value)))
        
        if other_fields:
            lines.append("")
            lines.append("ADDITIONAL INFORMATION")
            lines.append("-" * 21)
            for label, value in other_fields:
                lines.append(f"{label}: {value}")
        
        # Footer
        lines.append("")
        lines.append("-" * 80)
        lines.append(f"Generated by {org_name} Valuation System")
        lines.append(f"Report generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        lines.append("=" * 80)
        
        return "\n".join(lines)

    def get_available_templates(self) -> Dict[str, Any]:
        """
        Get list of available PDF templates
        """
        return {
            "templates": [
                {
                    "bank": "SBI",
                    "propertyType": "land",
                    "templateName": "SBI Land Property Valuation",
                    "available": True,
                    "generatorUsed": "Text-based (Development Fallback)",
                    "note": "Basic text format - PDF libraries not configured"
                }
            ],
            "capabilities": {
                "weasyprint": False,
                "reportlab": False,
                "currentGenerator": "Text-based fallback",
                "note": "Development mode - install PDF libraries for proper PDF generation"
            }
        }

# Create global instance
pdf_generator = PDFGenerator()