#!/usr/bin/env python3
"""
Update the report_reference_number field in common_fields to be read-only and auto-generated
"""

import os
import sys
from pymongo import MongoClient
from datetime import datetime

# Add parent directory to path for imports
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

def update_reference_number_field():
    """Update the report_reference_number field configuration"""
    
    # MongoDB connection - use environment variable or default
    mongo_uri = os.getenv('MONGODB_URI')
    if not mongo_uri:
        # Try to load from .env file
        env_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'backend', '.env')
        if os.path.exists(env_path):
            with open(env_path, 'r') as f:
                for line in f:
                    if line.startswith('MONGODB_URI='):
                        mongo_uri = line.split('=', 1)[1].strip()
                        break
    
    if not mongo_uri:
        print("❌ Error: MONGODB_URI not found in environment or backend/.env")
        sys.exit(1)
    
    print(f"🔗 Connecting to MongoDB...")
    client = MongoClient(mongo_uri)
    
    # Select database - use valuation_admin where the backend reads from
    db = client['valuation_admin']
    collection = db['common_form_fields']
    
    print("🔄 Updating report_reference_number field configuration in valuation_admin.common_form_fields...")
    
    # Updated field configuration
    updated_field = {
        "fieldId": "report_reference_number",
        "technicalName": "report_reference_number",
        "uiDisplayName": "Report Reference Number",
        "fieldType": "text",  # Keep as text but will be disabled in frontend
        "isRequired": True,
        "isReadonly": True,  # Match frontend naming convention (lowercase 'd')
        "isAutoGenerated": True,  # NEW: Mark as auto-generated
        "placeholder": "Auto-generated on save",
        "helpText": "Automatically generated unique reference number for this report (Format: INITIALS/0001/DDMMYYYY)",
        "validation": {
            # Remove the strict pattern since it's auto-generated
            "maxLength": 50  # Increased to accommodate longer formats
        },
        "gridSize": 3,
        "sortOrder": 1,
        "isActive": True,
        "updatedAt": datetime.utcnow().isoformat()
    }
    
    # Update the field in the array
    result = collection.update_one(
        {"_id": "common_fields"},
        {
            "$set": {
                "fields.$[elem]": updated_field,
                "updatedAt": datetime.utcnow()
            }
        },
        array_filters=[{"elem.fieldId": "report_reference_number"}]
    )
    
    if result.modified_count > 0:
        print("✅ Successfully updated report_reference_number field configuration")
        print("\n📋 Updated configuration:")
        print(f"   - Field Type: {updated_field['fieldType']}")
        print(f"   - Read-Only: {updated_field['isReadonly']}")
        print(f"   - Auto-Generated: {updated_field['isAutoGenerated']}")
        print(f"   - Help Text: {updated_field['helpText']}")
        print(f"   - Placeholder: {updated_field['placeholder']}")
        
        # Verify the update
        doc = collection.find_one({"_id": "common_fields"})
        if doc and 'fields' in doc:
            ref_field = next((f for f in doc['fields'] if f['fieldId'] == 'report_reference_number'), None)
            if ref_field:
                print("\n✅ Verification: Field updated successfully in database")
                print(f"   isReadonly: {ref_field.get('isReadonly', False)}")
                print(f"   isAutoGenerated: {ref_field.get('isAutoGenerated', False)}")
            else:
                print("\n⚠️ Warning: Could not find field in verification check")
    else:
        print("⚠️ No changes made - field may already be updated or not found")
    
    client.close()
    print("\n✅ Database update complete!")

if __name__ == "__main__":
    try:
        update_reference_number_field()
    except Exception as e:
        print(f"❌ Error updating field: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
